"""A paper level index tying every figure and table to its inputs.

Each package carries its own manifest, and each manifest knows the hashes of
its own files, but nothing connects a float printed in the manuscript to the
archive it came from.  This module builds that connection: for every figure
and every numbered table in the manuscript it records the artifact drawn, the
command that regenerates it, the package that owns it, and whether that
package can currently certify the provenance of the simulations behind it.

The index is derived, never authored: figures are read out of the manuscript
source, and artifact hashes are read out of the package manifests, so an index
that disagrees with the repository is a failure rather than a stale document.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from pathlib import Path


MANUSCRIPT = Path("paper/SdS.tex")
OUTPUT = Path("docs/EVIDENCE_INDEX.md")
RECORD = Path("docs/evidence_index.json")

# The manuscript uses \includegraphics once a figure is final and the
# \draftgraphic placeholder while one is still missing.  Both count as a
# citation for indexing purposes.
GRAPHIC = re.compile(
    r"\\(?:includegraphics|draftgraphic)(?:\[[^\]]*\])?\{([^}]*)\}"
)
LABEL = re.compile(r"\\label\{(tab:[^}]*)\}")

REGULATOR_PACKAGE = "results/regulator_production_v3"
TAIL_PACKAGE = "results/large_l_tail"

REGULATOR_COMMAND = (
    "python -m black_hole.regulator_analysis --output-dir " + REGULATOR_PACKAGE
)
TAIL_COMMAND = (
    "python -m black_hole.large_l_tail --output-dir " + TAIL_PACKAGE
    + " report-final 5120"
)


@dataclass(frozen=True)
class Source:
    """Where one manuscript artifact comes from."""

    package: str
    command: str
    artifact: str | None = None
    note: str = ""
    supplied: bool = False


@dataclass
class Entry:
    kind: str
    name: str
    source: Source
    manifest_path: str | None = None
    sha256: str | None = None
    issues: list[str] = field(default_factory=list)


# Figures are keyed by the basename used in the manuscript.  The artifact is
# the file inside the owning package that the paper copy was taken from.
FIGURES: dict[str, Source] = {
    "minimalAnil.pdf": Source(
        package="paper", command="supplied with the manuscript",
        note="conformal diagram, not generated by this repository", supplied=True,
    ),
    "minimalRodrigo.pdf": Source(
        package="paper", command="supplied with the manuscript",
        note="conformal diagram, not generated by this repository", supplied=True,
    ),
    "foliation_flat_limit.pdf": Source(
        package="paper",
        command="python -m black_hole.foliation_diagnostics",
        note="foliation diagnostic, reproducible from the analytic formulas",
    ),
    "flat_waveform_sequence.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/flat_waveform_sequence.pdf",
    ),
    "flat_window_errors.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/flat_window_errors.pdf",
    ),
    "nested_extrapolants.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/nested_extrapolants.pdf",
    ),
    "localized_source_regulator.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/localized_source_regulator.pdf",
    ),
    "D1_scaling.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/D1_scaling.pdf",
    ),
    "D1_error_separation.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/D1_error_separation.pdf",
    ),
    "L12_phase_exclusion.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/L12_phase_exclusion.pdf",
    ),
}

TABLES: dict[str, Source] = {
    "tab:flat_windows": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/flat_waveform_metrics.csv",
        note="direct errors on the declared windows",
    ),
    "tab:extrapolants": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/flat_extrapolant_comparisons.csv",
        note="headline nested extrapolants",
    ),
    "tab:localized": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=(
            f"{REGULATOR_PACKAGE}/tables/"
            "localized_source_extrapolant_comparisons.csv"
        ),
        note="sphere integrated modal norm on the common archived interval",
    ),
    "tab:extrapolant_audit": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/flat_extrapolant_comparisons.csv",
        note="full audit including the diagnostic disjoint windows",
    ),
    "tab:timing": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/D1_measurements.csv",
        note="deterministic timing sensitivities",
    ),
}

# Results that exist in the repository and are intended for the manuscript but
# are not yet cited by it.  Listing them keeps the index honest about what is
# assembled and what is still outstanding.
PENDING: dict[str, Source] = {
    "large_L5120_tail_transition.pdf": Source(
        package=TAIL_PACKAGE, command=TAIL_COMMAND,
        artifact=f"{TAIL_PACKAGE}/large_L5120_tail_transition.pdf",
        note="three panel tail figure, intended for the main text",
    ),
    "final_L5120_ladder_floor.csv": Source(
        package=TAIL_PACKAGE, command=TAIL_COMMAND,
        artifact=f"{TAIL_PACKAGE}/tables/final_L5120_ladder_floor.csv",
        note="measured ladder floor and trusted window per observer",
    ),
    "final_L5120_numerical_sensitivities.csv": Source(
        package=TAIL_PACKAGE, command=TAIL_COMMAND,
        artifact=f"{TAIL_PACKAGE}/tables/final_L5120_numerical_sensitivities.csv",
        note="three level and timestep sensitivities",
    ),
    "extrapolation_robustness_summary.csv": Source(
        package=REGULATOR_PACKAGE,
        command="python -m black_hole.regulator_robustness",
        artifact=(
            f"{REGULATOR_PACKAGE}/tables/extrapolation_robustness_summary.csv"
        ),
        note="alternative truncations and subsets, intended for an appendix",
    ),
}


def _load_manifest(package: str, root: Path) -> dict:
    path = root / package / "manifest.json"
    if not path.exists():
        return {}
    manifest = json.loads(path.read_text(encoding="utf-8"))
    lookup = {}
    for section in ("archives", "derived_artifacts"):
        for row in manifest.get(section, []):
            lookup[row["path"]] = row
    return {
        "rows": lookup,
        "simulation_commits": manifest.get("simulation_commits", []),
        "analysis_commit": manifest.get("analysis_commit"),
        "grades": sorted(
            {
                row.get("provenance_grade", "unrecorded")
                for row in manifest.get("archives", [])
            }
        ),
    }


def _cited(manuscript: Path) -> tuple[list[str], list[str]]:
    text = manuscript.read_text(encoding="utf-8")
    figures = [Path(match).name for match in GRAPHIC.findall(text)]
    tables = LABEL.findall(text)
    return figures, tables


def build(root: Path = Path(".")) -> dict:
    """Return the index and every inconsistency found while building it."""

    root = root.resolve()
    manuscript = root / MANUSCRIPT
    figures, tables = _cited(manuscript)
    manifests = {
        package: _load_manifest(package, root)
        for package in (REGULATOR_PACKAGE, TAIL_PACKAGE)
    }

    entries: list[Entry] = []
    problems: list[str] = []

    def record(kind: str, name: str, source: Source) -> None:
        entry = Entry(kind=kind, name=name, source=source)
        if source.artifact:
            artifact = root / source.artifact
            if not artifact.exists():
                entry.issues.append("artifact missing from the repository")
            manifest = manifests.get(source.package) or {}
            row = (manifest.get("rows") or {}).get(source.artifact)
            if row is None:
                entry.issues.append("artifact not recorded in the package manifest")
            else:
                entry.manifest_path = source.artifact
                entry.sha256 = row["sha256"]
        entries.append(entry)
        for issue in entry.issues:
            problems.append(f"{kind} {name}: {issue}")

    for name in figures:
        source = FIGURES.get(name)
        if source is None:
            problems.append(f"figure {name}: cited by the manuscript but not indexed")
            continue
        record("figure", name, source)
    for name in tables:
        source = TABLES.get(name)
        if source is None:
            problems.append(f"table {name}: labelled in the manuscript but not indexed")
            continue
        record("table", name, source)
    for name, source in PENDING.items():
        record("pending", name, source)

    for name in FIGURES:
        if name not in figures:
            problems.append(f"figure {name}: indexed but not cited by the manuscript")
    for name in TABLES:
        if name not in tables:
            problems.append(f"table {name}: indexed but not labelled in the manuscript")

    return {
        "manuscript": MANUSCRIPT.as_posix(),
        "entries": [
            {
                "kind": entry.kind,
                "name": entry.name,
                "package": entry.source.package,
                "artifact": entry.source.artifact,
                "command": entry.source.command,
                "note": entry.source.note,
                "sha256": entry.sha256,
                "issues": entry.issues,
            }
            for entry in entries
        ],
        "packages": {
            package: {
                "analysis_commit": (manifests[package] or {}).get("analysis_commit"),
                "simulation_commits": (manifests[package] or {}).get(
                    "simulation_commits", []
                ),
                "provenance_grades": (manifests[package] or {}).get("grades", []),
            }
            for package in manifests
        },
        "problems": problems,
    }


def render(index: dict) -> str:
    """Return the index as a document."""

    lines = [
        "# Evidence index",
        "",
        "Every figure and numbered table in "
        f"[`{index['manuscript']}`](../{index['manuscript']}) with the artifact "
        "it draws, the command that regenerates that artifact, and the package "
        "manifest entry that fixes its hash.",
        "",
        "This file is generated by `python -m black_hole.evidence_index`. It is "
        "not edited by hand, and a disagreement with the repository is reported "
        "as a problem rather than silently absorbed.",
        "",
        "## Packages",
        "",
        "| package | analysis commit | simulation commits | provenance |",
        "|---|---|---|---|",
    ]
    for package, record in index["packages"].items():
        commits = ", ".join(
            f"`{value[:12]}`" for value in record.get("simulation_commits", [])
        ) or "n/a"
        analysis = record.get("analysis_commit")
        lines.append(
            f"| `{package}` | `{(analysis or 'n/a')[:12]}` | {commits} | "
            f"{', '.join(record.get('provenance_grades') or ['n/a'])} |"
        )

    for kind, title, blurb in (
        ("figure", "Figures in the manuscript", ""),
        ("table", "Tables in the manuscript", ""),
        (
            "pending",
            "Assembled but not yet cited",
            "These results exist and are verified, and are intended for the "
            "manuscript once their placement is settled.",
        ),
    ):
        rows = [entry for entry in index["entries"] if entry["kind"] == kind]
        if not rows:
            continue
        lines += ["", f"## {title}", ""]
        if blurb:
            lines += [blurb, ""]
        lines += [
            "| name | artifact | regenerate with | sha256 |",
            "|---|---|---|---|",
        ]
        for entry in rows:
            digest = f"`{entry['sha256'][:12]}`" if entry["sha256"] else "not recorded"
            artifact = f"`{entry['artifact']}`" if entry["artifact"] else entry["note"]
            lines.append(
                f"| `{entry['name']}` | {artifact} | `{entry['command']}` | {digest} |"
            )

    problems = index["problems"]
    lines += ["", "## Consistency", ""]
    if problems:
        lines.append(
            f"{len(problems)} item(s) need attention:"
        )
        lines.append("")
        lines += [f"* {problem}" for problem in problems]
    else:
        lines.append(
            "Every cited figure and table is indexed, present, and recorded in "
            "its package manifest."
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--check", action="store_true",
                        help="exit non zero when the index finds a problem")
    arguments = parser.parse_args()
    index = build(arguments.root)
    (arguments.root / OUTPUT).write_text(render(index), encoding="utf-8")
    (arguments.root / RECORD).write_text(
        json.dumps(index, indent=2), encoding="utf-8"
    )
    print(f"{OUTPUT} written with {len(index['entries'])} entries")
    for problem in index["problems"]:
        print("  problem:", problem)
    if arguments.check and index["problems"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
