"""A paper level index tying every figure and table to its inputs.

Each package carries its own manifest, and each manifest knows the hashes of
its own files, but nothing connects a float printed in the manuscript to the
archive it came from.  This module builds that connection: for every figure
and every numbered table in the manuscript it records the artifact drawn, the
command that regenerates it, the package that owns it, and whether that
package can currently certify the provenance of the simulations behind it.

The index is derived, never authored: figures are read out of the manuscript
source, and artifact hashes are read out of the package manifests, so an index
that disagrees with the repository is a failure rather than a stale document.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path


MANUSCRIPT = Path("paper/SdS.tex")
OUTPUT = Path("docs/EVIDENCE_INDEX.md")
RECORD = Path("docs/evidence_index.json")

# The manuscript uses \includegraphics once a figure is final and the
# \draftgraphic placeholder while one is still missing.  Both count as a
# citation for indexing purposes.
GRAPHIC = re.compile(
    r"\\(?:includegraphics|draftgraphic)(?:\[[^\]]*\])?\{([^}]*)\}"
)
LABEL = re.compile(r"\\label\{(tab:[^}]*)\}")

REGULATOR_PACKAGE = "results/regulator_production_v3"
QNM_PACKAGE = "results/exterior_regulator_width_floor_qnm_v5"
MATCHED_TAIL_PACKAGE = "results/curvature_coupling_production_v2"

MANIFEST_NAMES = {
    REGULATOR_PACKAGE: "manifest.json",
    QNM_PACKAGE: "manifest.json",
    MATCHED_TAIL_PACKAGE: "tail_manifest.json",
}

REGULATOR_COMMAND = (
    "python -m black_hole.regulator_analysis --output-dir " + REGULATOR_PACKAGE
)
QNM_COMMAND = (
    "python -m black_hole.far_regulator_production_analysis "
    f"--output-dir {QNM_PACKAGE} "
    f"--control-dir {REGULATOR_PACKAGE} "
    "--legacy-candidate-dir results/exterior_regulator_far_production_v1"
)
MATCHED_TAIL_COMMAND = (
    "python -m black_hole.curvature_coupling_tail_analysis "
    f"--root {MATCHED_TAIL_PACKAGE}"
)


@dataclass(frozen=True)
class Source:
    """Where one manuscript artifact comes from."""

    package: str
    command: str
    artifact: str | None = None
    note: str = ""
    supplied: bool = False


@dataclass
class Entry:
    kind: str
    name: str
    source: Source
    manifest_path: str | None = None
    sha256: str | None = None
    issues: list[str] = field(default_factory=list)


# Figures are keyed by the basename used in the manuscript.  The artifact is
# the owning package's source figure.  Submission copies may be rendered again
# with embedded-font settings, so the index does not require identical PDF
# container bytes.
FIGURES: dict[str, Source] = {
    "minimalAnil.pdf": Source(
        package="paper", command="supplied with the manuscript",
        note="conformal diagram, not generated by this repository", supplied=True,
    ),
    "minimalRodrigo.pdf": Source(
        package="paper", command="supplied with the manuscript",
        note="conformal diagram, not generated by this repository", supplied=True,
    ),
    "foliation_flat_limit.pdf": Source(
        package="paper",
        command="python -m black_hole.foliation_diagnostics",
        note="foliation diagnostic, reproducible from the analytic formulas",
    ),
    "flat_waveform_sequence.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/flat_waveform_sequence.pdf",
    ),
    "flat_window_errors.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/flat_window_errors.pdf",
    ),
    "nested_extrapolants.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/nested_extrapolants.pdf",
    ),
    "localized_source_regulator.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/localized_source_regulator.pdf",
    ),
    "exterior_qnm_residual_comparison.pdf": Source(
        package=QNM_PACKAGE, command=QNM_COMMAND,
        artifact=f"{QNM_PACKAGE}/width_floor_qnm_residual_comparison.pdf",
        note="raw QNM-window residuals against the frozen Schwarzschild control",
    ),
    "tail_outer_boundary_comparison.pdf": Source(
        package=MATCHED_TAIL_PACKAGE, command=MATCHED_TAIL_COMMAND,
        artifact=f"{MATCHED_TAIL_PACKAGE}/tail_outer_boundary_comparison.pdf",
        note="matched outer-boundary tail comparison",
    ),
    "D1_scaling.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/D1_scaling.pdf",
    ),
    "D1_error_separation.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/D1_error_separation.pdf",
    ),
    "L12_phase_exclusion.pdf": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/L12_phase_exclusion.pdf",
    ),
}

TABLES: dict[str, Source] = {
    "tab:flat_windows": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/flat_waveform_metrics.csv",
        note="direct errors on the declared windows",
    ),
    "tab:extrapolants": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/flat_extrapolant_comparisons.csv",
        note="headline nested extrapolants",
    ),
    "tab:localized": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=(
            f"{REGULATOR_PACKAGE}/tables/"
            "localized_source_extrapolant_comparisons.csv"
        ),
        note="sphere integrated modal norm on the common archived interval",
    ),
    "tab:exterior-qnm-improvement": Source(
        package=QNM_PACKAGE, command=QNM_COMMAND,
        artifact=f"{QNM_PACKAGE}/tables/width_floor_vs_uniform_raw.csv",
        note="unshifted QNM-window errors, refinement scales, and reductions",
    ),
    "tab:matched-tail": Source(
        package=MATCHED_TAIL_PACKAGE, command=MATCHED_TAIL_COMMAND,
        artifact=f"{MATCHED_TAIL_PACKAGE}/tables/tail_price_intervals.csv",
        note="accepted Price-index intervals and pass/fail classifications",
    ),
    "tab:extrapolant_audit": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/flat_extrapolant_comparisons.csv",
        note="full audit including the diagnostic disjoint windows",
    ),
    "tab:timing": Source(
        package=REGULATOR_PACKAGE, command=REGULATOR_COMMAND,
        artifact=f"{REGULATOR_PACKAGE}/tables/D1_measurements.csv",
        note="deterministic timing sensitivities",
    ),
}


def _manifest_row_path(
    package: str, section: str, row_path: str, manifest: dict
) -> str:
    """Return a repository-relative path for one manifest row.

    The regulator and QNM manifests store repository-relative paths.  The
    matched-tail manifest deliberately stores its raw and derived package
    contents relative to the package root, while its formulation controls and
    source files remain repository-relative.  Its verification block records
    that distinction explicitly; honor it instead of guessing from whether a
    file happens to exist.
    """

    scope = (
        manifest.get("verification", {})
        .get("path_scopes", {})
        .get(section, "")
    )
    if "relative to the matched-tail package" in scope:
        return (Path(package) / row_path).as_posix()
    return Path(row_path).as_posix()


def _load_manifest(package: str, root: Path) -> dict:
    path = root / package / MANIFEST_NAMES.get(package, "manifest.json")
    if not path.exists():
        return {}
    manifest = json.loads(path.read_text(encoding="utf-8"))
    lookup = {}
    archive_rows = []
    for section in (
        "archives",
        "raw_archives",
        "formulation_control_archives",
        "external_inputs",
        "source_files",
        "derived_artifacts",
    ):
        for row in manifest.get(section, []):
            normalized = _manifest_row_path(
                package, section, row["path"], manifest
            )
            lookup[normalized] = row
            if section in (
                "archives", "raw_archives", "formulation_control_archives"
            ):
                archive_rows.append(row)

    # The packages span three generations of provenance schema.  Preserve
    # exact simulation commits where they exist, and use the named campaign
    # records when the matched-tail package instead freezes its source by hash.
    commits = manifest.get("simulation_commits")
    if not commits:
        single = manifest.get("simulation_commit")
        commits = [single] if single else sorted(
            {
                commit
                for row in archive_rows
                for commit in (
                    row.get("simulation_commit"),
                    row.get("simulation_git_base_commit"),
                    row.get("archived_git_commit"),
                )
                if commit
            }
        )
    campaign_ids = [
        row["campaign_id"] for row in manifest.get("simulation_campaigns", [])
    ]
    grades = sorted(
        {
            row["provenance_grade"]
            for row in archive_rows
            if row.get("provenance_grade")
        }
    )
    if not grades and manifest.get("archives"):
        # The regulator package predates the grade field; its creation refuses
        # any archive that records a dirty worktree, so every entry is clean.
        grades = ["production (enforced at manifest creation)"]
    if not grades and manifest.get("raw_archives"):
        grades = ["hash-verified campaign archives"]
        if any(
            row.get("archived_worktree_dirty")
            for row in manifest.get("formulation_control_archives", [])
        ):
            grades.append("formulation controls retained as screening evidence")

    analysis_revision = manifest.get("analysis_commit")
    if not analysis_revision and manifest.get("analysis_git_base_commit"):
        analysis_revision = "base " + manifest["analysis_git_base_commit"]
        if manifest.get("source_hashes_are_authoritative"):
            analysis_revision += " + authoritative source hashes"
    if not analysis_revision:
        source_hash = manifest.get("analysis", {}).get("source_sha256")
        if source_hash:
            analysis_revision = "source " + source_hash
    return {
        "rows": lookup,
        "simulation_commits": commits,
        "simulation_records": [*commits, *campaign_ids],
        "analysis_revision": analysis_revision,
        "grades": grades,
        "manifest_path": path.relative_to(root).as_posix(),
    }


def _cited(manuscript: Path) -> tuple[list[str], list[str]]:
    text = manuscript.read_text(encoding="utf-8")
    figures = [Path(match).name for match in GRAPHIC.findall(text)]
    tables = LABEL.findall(text)
    return figures, tables


def _artifact_sha256(path: Path, hash_mode: str) -> str:
    """Hash an artifact using the convention declared by its manifest."""

    data = path.read_bytes()
    if hash_mode == "sha256_utf8_canonical_lf_v1":
        text = data.decode("utf-8").replace("\r\n", "\n").replace("\r", "\n")
        data = text.encode("utf-8")
    elif hash_mode not in ("sha256_bytes", ""):
        raise ValueError(f"unsupported manifest hash mode: {hash_mode}")
    return hashlib.sha256(data).hexdigest()


def build(root: Path = Path(".")) -> dict:
    """Return the index and every inconsistency found while building it."""

    root = root.resolve()
    manuscript = root / MANUSCRIPT
    figures, tables = _cited(manuscript)
    manifests = {
        package: _load_manifest(package, root)
        for package in MANIFEST_NAMES
    }

    entries: list[Entry] = []
    problems: list[str] = []

    def record(kind: str, name: str, source: Source) -> None:
        entry = Entry(kind=kind, name=name, source=source)
        if kind == "figure":
            manuscript_figure = root / MANUSCRIPT.parent / "figs" / name
            if not manuscript_figure.exists():
                entry.issues.append("manuscript figure file is missing")
        if source.artifact:
            artifact = root / source.artifact
            if not artifact.exists():
                entry.issues.append("artifact missing from the repository")
            manifest = manifests.get(source.package) or {}
            row = (manifest.get("rows") or {}).get(source.artifact)
            if row is None:
                entry.issues.append("artifact not recorded in the package manifest")
            elif artifact.exists():
                entry.manifest_path = source.artifact
                entry.sha256 = row["sha256"]
                try:
                    actual = _artifact_sha256(
                        artifact, row.get("hash_mode", "sha256_bytes")
                    )
                except (UnicodeDecodeError, ValueError) as error:
                    entry.issues.append(str(error))
                else:
                    if actual != entry.sha256:
                        entry.issues.append("artifact hash disagrees with its manifest")
        entries.append(entry)
        for issue in entry.issues:
            problems.append(f"{kind} {name}: {issue}")

    for name in figures:
        source = FIGURES.get(name)
        if source is None:
            problems.append(f"figure {name}: cited by the manuscript but not indexed")
            continue
        record("figure", name, source)
    for name in tables:
        source = TABLES.get(name)
        if source is None:
            problems.append(f"table {name}: labelled in the manuscript but not indexed")
            continue
        record("table", name, source)
    for name in FIGURES:
        if name not in figures:
            problems.append(f"figure {name}: indexed but not cited by the manuscript")
    for name in TABLES:
        if name not in tables:
            problems.append(f"table {name}: indexed but not labelled in the manuscript")

    return {
        "manuscript": MANUSCRIPT.as_posix(),
        "entries": [
            {
                "kind": entry.kind,
                "name": entry.name,
                "package": entry.source.package,
                "artifact": entry.source.artifact,
                "command": entry.source.command,
                "note": entry.source.note,
                "sha256": entry.sha256,
                "issues": entry.issues,
            }
            for entry in entries
        ],
        "packages": {
            package: {
                "manifest": (manifests[package] or {}).get("manifest_path"),
                "analysis_revision": (manifests[package] or {}).get(
                    "analysis_revision"
                ),
                "simulation_commits": (manifests[package] or {}).get(
                    "simulation_commits", []
                ),
                "simulation_records": (manifests[package] or {}).get(
                    "simulation_records", []
                ),
                "provenance_grades": (manifests[package] or {}).get("grades", []),
            }
            for package in manifests
        },
        "problems": problems,
    }


def render(index: dict) -> str:
    """Return the index as a document."""

    def short_identity(value: str) -> str:
        if len(value) in (40, 64) and re.fullmatch(r"[0-9a-f]+", value):
            return value[:12]
        return value

    lines = [
        "# Evidence index",
        "",
        "Every figure and numbered table in "
        f"[`{index['manuscript']}`](../{index['manuscript']}) with the artifact "
        "it draws, the command that regenerates that artifact, and the package "
        "manifest entry that fixes its hash.",
        "",
        "This file is generated by `python -m black_hole.evidence_index`. It is "
        "not edited by hand, and a disagreement with the repository is reported "
        "as a problem rather than silently absorbed.",
        "",
        "Submission figures may be rendered again with embedded-font settings; "
        "the indexed file is the manifest-verified source artifact, not a claim "
        "that every PDF container in `paper/figs` is byte-identical.",
        "",
        "## Packages",
        "",
        "| package manifest | analysis revision | simulation records | provenance |",
        "|---|---|---|---|",
    ]
    for package, record in index["packages"].items():
        simulation_records = ", ".join(
            f"`{short_identity(value)}`"
            for value in record.get("simulation_records", [])
        ) or "n/a"
        analysis = record.get("analysis_revision") or "n/a"
        if analysis.startswith(("base ", "source ")):
            words = analysis.split()
            analysis = " ".join(
                short_identity(word) for word in words
            )
        else:
            analysis = short_identity(analysis)
        manifest = record.get("manifest") or f"{package}/manifest missing"
        lines.append(
            f"| `{manifest}` | `{analysis}` | {simulation_records} | "
            f"{', '.join(record.get('provenance_grades') or ['n/a'])} |"
        )

    for kind, title in (
        ("figure", "Figures in the manuscript"),
        ("table", "Tables in the manuscript"),
    ):
        rows = [entry for entry in index["entries"] if entry["kind"] == kind]
        if not rows:
            continue
        lines += ["", f"## {title}", ""]
        lines += [
            "| name | artifact | regenerate with | sha256 |",
            "|---|---|---|---|",
        ]
        for entry in rows:
            digest = f"`{entry['sha256'][:12]}`" if entry["sha256"] else "not recorded"
            artifact = f"`{entry['artifact']}`" if entry["artifact"] else entry["note"]
            lines.append(
                f"| `{entry['name']}` | {artifact} | `{entry['command']}` | {digest} |"
            )

    problems = index["problems"]
    lines += ["", "## Consistency", ""]
    if problems:
        lines.append(
            f"{len(problems)} item(s) need attention:"
        )
        lines.append("")
        lines += [f"* {problem}" for problem in problems]
    else:
        lines.append(
            "Every cited figure and table is indexed, present, and recorded in "
            "its package manifest."
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--check", action="store_true",
                        help="exit non zero when the index finds a problem")
    arguments = parser.parse_args()
    index = build(arguments.root)
    (arguments.root / OUTPUT).write_text(render(index), encoding="utf-8")
    (arguments.root / RECORD).write_text(
        json.dumps(index, indent=2), encoding="utf-8"
    )
    print(f"{OUTPUT} written with {len(index['entries'])} entries")
    for problem in index["problems"]:
        print("  problem:", problem)
    if arguments.check and index["problems"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
